import type { Metadata } from 'next';
import './globals.css';
import './themes.css';
import { css } from '@/styled-system/css';

import { Navbar } from '@/components/Navbar';
import { Sidebar } from '@/components/Sidebar';
import { AppLayout } from '@/components/AppLayout';
import { getHomeData, getCodeInjection, getCssInjection, getAllPosts, getAdvancedConfig } from '@/lib/data';
import { GlobalConfigProvider } from '@/components/providers/GlobalConfigProvider';
import { ExperimentPanel } from '@/components/ExperimentPanel';


export async function generateMetadata(): Promise<Metadata> {
    const homeData = getHomeData();
    const title = homeData.info?.title || 'My Portfolio';
    const description = homeData.info?.description || 'Generated by Notion as a Website';
    const keywords = homeData.info?.keywords;
    const ogImage = homeData.info?.og_image;

    return {
        metadataBase: new URL(process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000'),
        title: title,
        description: description,
        ...(keywords ? { keywords: keywords.split(',').map(k => k.trim()) } : {}),
        openGraph: {
            title: title,
            description: description,
            images: ogImage ? [{ url: ogImage }] : [],
        },
        twitter: {
            card: 'summary_large_image',
            title: title,
            description: description,
            ...(ogImage ? { images: [ogImage] } : {}),
        },
    };
}

function buildGoogleFontsUrl(primaryFont: string, secondaryFont: string): string | null {
    const fonts = new Set<string>();
    if (primaryFont) fonts.add(primaryFont);
    if (secondaryFont && secondaryFont !== primaryFont) fonts.add(secondaryFont);
    if (fonts.size === 0) return null;

    const families = Array.from(fonts)
        .map(f => `family=${encodeURIComponent(f)}:wght@400;500;600;700;800`)
        .join('&');
    return `https://fonts.googleapis.com/css2?${families}&display=swap`;
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const homeData = getHomeData();
    const defaultTheme = homeData.info?.default_color_mode || 'light';

    // Code injection: get all code blocks to inject into <head>
    const codeInjectionBlocks = getCodeInjection();
    const cssInjectionBlocks = getCssInjection();

    // Advanced config (theme filtering + fonts)
    const advancedConfig = getAdvancedConfig();
    const allowedThemes = advancedConfig.limit_theme_selection;
    const primaryFont = homeData.info?.primary_font || 'Inter';
    const secondaryFont = homeData.info?.secondary_font || primaryFont;
    const googleFontsUrl = buildGoogleFontsUrl(primaryFont, secondaryFont);

    // Build search index from all posts
    const allPosts = getAllPosts();
    const searchIndex = allPosts.map(p => ({
        slug: p.slug,
        title: p.title,
        description: p.description || '',
        collection: p.collection || '',
        tags: p.tags || [],
    }));

    // Build font CSS variables
    const fontVarsCSS = `
        :root {
            --font-primary: '${primaryFont}', sans-serif;
            --font-secondary: '${secondaryFont}', sans-serif;
        }
    `;

    // Merge all code injection blocks into a single script-safe string
    const codeInjectionHtml = codeInjectionBlocks.join('\n');

    return (
        <html lang="en" suppressHydrationWarning>
            <head>
                <script dangerouslySetInnerHTML={{
                    __html: `
                    (function() {
                        try {
                            var saved = localStorage.getItem('swan-color-mode');
                            var themes = ['light','cream','pink','dark','blue','purple','red','green'];
                            var theme = (saved && themes.indexOf(saved) !== -1) ? saved : ${JSON.stringify(defaultTheme)};
                            document.documentElement.setAttribute('data-theme', theme);
                        } catch(e) {
                            document.documentElement.setAttribute('data-theme', ${JSON.stringify(defaultTheme)});
                        }
                    })();
                `}} />
                {homeData.info?.favicon && <link rel="icon" href={homeData.info.favicon} sizes="any" />}
                {googleFontsUrl && (
                    <>
                        <link rel="preconnect" href="https://fonts.googleapis.com" />
                        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
                        <link rel="stylesheet" href={googleFontsUrl} />
                    </>
                )}
                <style dangerouslySetInnerHTML={{ __html: fontVarsCSS }} />
                {codeInjectionHtml && (
                    <script dangerouslySetInnerHTML={{ __html: codeInjectionHtml }} />
                )}
                {cssInjectionBlocks.map((cssCode, index) => (
                    <style
                        key={`css-injection-${index}`}
                        dangerouslySetInnerHTML={{ __html: cssCode }}
                    />
                ))}
            </head>
            <body
                className={css({ bg: 'bg.primary', color: 'text.primary' })}
            >
                <GlobalConfigProvider initialConfig={homeData} searchIndex={searchIndex} allowedThemes={allowedThemes}>
                    <AppLayout
                        sidebar={<Sidebar />}
                        navbar={<Navbar />}
                    >
                        {children}
                    </AppLayout>
                    {process.env.NODE_ENV !== 'production' && <ExperimentPanel />}
                </GlobalConfigProvider>
            </body>
        </html>
    );
}
