import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { css } from '@/styled-system/css';

import { Navbar } from '@/components/Navbar';
import { Sidebar } from '@/components/Sidebar';
import { getHomeData } from '@/lib/data';
import { DevTools } from '@/components/DevTools';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'My Portfolio',
    description: 'Generated by Notion as a Website',
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const homeData = getHomeData();
    const showSidebar = homeData.info?.sidebar_navigation === 'true';

    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${inter.className} ${css({ bg: 'bg.primary', color: 'text.primary' })}`}>
                <script
                    dangerouslySetInnerHTML={{
                        __html: `!function(){try{var e=localStorage.getItem("theme"),t="${homeData.info?.default_theme || "light"}";var a=e||t;if("dark"===a||(!e&&"system"===t&&window.matchMedia("(prefers-color-scheme: dark)").matches)){document.documentElement.classList.add("dark");document.documentElement.setAttribute("data-theme","dark")}else{document.documentElement.classList.remove("dark");document.documentElement.setAttribute("data-theme","light")}}catch(e){}}();`,
                    }}
                />
                {showSidebar ? (
                    <>
                        <Sidebar />
                        <div className={css({
                            ml: '300px', // 20px (left) + 260px (width) + 20px (gap)
                            minH: '100vh',
                            display: 'flex',
                            justifyContent: 'center', // Center content horizontally
                            width: 'calc(100% - 300px)', // Distinct width calculation
                        })}>
                            <div className={css({
                                width: '100%',
                                maxWidth: '1000px',
                                p: '40px',
                            })}>
                                {children}
                            </div>
                        </div>
                    </>
                ) : (
                    <div className={css({ maxWidth: '800px', mx: 'auto', px: '20px' })}>
                        <Navbar />
                        {children}
                    </div>
                )}
                {process.env.NODE_ENV === 'development' && <DevTools />}
            </body>
        </html>
    );
}
