import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import './themes.css';
import { css } from '@/styled-system/css';

import { Navbar } from '@/components/Navbar';
import { Sidebar } from '@/components/Sidebar';
import { AppLayout } from '@/components/AppLayout';
import { getHomeData, getCodeInjection, getAllPosts } from '@/lib/data';
import { GlobalConfigProvider } from '@/components/providers/GlobalConfigProvider';


const inter = Inter({ subsets: ['latin'] });

export async function generateMetadata(): Promise<Metadata> {
    const homeData = getHomeData();
    const title = homeData.info?.title || 'My Portfolio';
    const description = homeData.info?.description || 'Generated by Notion as a Website';

    return {
        metadataBase: new URL(process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000'),
        title: title,
        description: description,
        openGraph: {
            title: title,
            description: description,
            images: homeData.info?.og_image ? [{ url: homeData.info.og_image }] : [],
        },
    };
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const homeData = getHomeData();
    const defaultTheme = homeData.info?.default_color_mode || 'light';

    // Code injection: get all code blocks to inject into <head>
    const codeInjectionBlocks = getCodeInjection();

    // Build search index from all posts
    const allPosts = getAllPosts();
    const searchIndex = allPosts.map(p => ({
        slug: p.slug,
        title: p.title,
        description: p.description || '',
        collection: p.collection || '',
        tags: p.tags?.map(t => typeof t === 'string' ? t : (t as any).name) || [],
    }));

    return (
        <html lang="en" data-theme={defaultTheme} className={defaultTheme === 'dark' ? 'dark' : ''}>
            <head>
                {homeData.info?.favicon && <link rel="icon" href={homeData.info.favicon} sizes="any" />}
                {codeInjectionBlocks.map((code, index) => (
                    <script
                        key={`code-injection-${index}`}
                        dangerouslySetInnerHTML={{ __html: code }}
                    />
                ))}
            </head>
            <body
                className={`${inter.className} ${css({ bg: 'bg.primary', color: 'text.primary' })}`}
            >
                <GlobalConfigProvider initialConfig={homeData} searchIndex={searchIndex}>
                    <AppLayout
                        sidebar={<Sidebar />}
                        navbar={<Navbar />}
                    >
                        {children}
                    </AppLayout>
                </GlobalConfigProvider>
            </body>
        </html>
    );
}
